#include "Ent/EntDialect.h"
#include "Ent/EntOps.h"
#include "Ent/Structure.h"
#include "Ent/World.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Tools/mlir-translate/MlirTranslateMain.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/FormatVariadic.h"

using namespace mlir;
using namespace mlir::ent;

/// The C type that holds one element of `type` in world storage.
static StringRef getCType(Type type) {
  if (isa<EntityType>(type))
    return "ent_entity";
  if (isa<IndexType>(type))
    return "int64_t";
  if (auto integer = dyn_cast<IntegerType>(type)) {
    switch (integer.getWidth()) {
    case 1:
      return "bool";
    case 8:
      return "int8_t";
    case 16:
      return "int16_t";
    case 32:
      return "int32_t";
    case 64:
      return "int64_t";
    }
  }
  if (type.isF32())
    return "float";
  if (type.isF64())
    return "double";
  return {};
}

/// Replace every character that cannot appear in a C identifier by '_'.
static std::string toIdentifier(StringRef name) {
  std::string result;
  for (char c : name)
    result += llvm::isAlnum(c) ? c : '_';
  if (result.empty() || llvm::isDigit(result.front()))
    result.insert(result.begin(), '_');
  return result;
}

/// Emit the C API of the world and the schedules of `module`: creation,
/// counts, typed column accessors and one entry point per schedule. The
/// header is the only place a host needs to know the layout.
static LogicalResult emitHeader(ModuleOp module, raw_ostream &os) {
  // The same archetypes the lowering infers, under the same names.
  if (failed(inferArchetypes(module)))
    return failure();
  FailureOr<WorldLayout> layout = WorldLayout::compute(module);
  if (failed(layout))
    return failure();

  // Distinct names in the program may map to the same C identifier.
  llvm::StringSet<> names;
  auto claim = [&](Operation *op, const std::string &name) -> LogicalResult {
    if (!names.insert(name).second)
      return op->emitError("C name '") << name << "' is generated twice";
    return success();
  };

  os << "// Generated by ent-translate --ent-to-c-header. Do not edit.\n"
        "//\n"
        "// The world is one arena with a layout fixed at compile time. "
        "Create it,\n"
        "// spawn entities (ent_<Archetype>_spawn), fill their columns, and "
        "run\n"
        "// schedules on it.\n\n"
        "#ifndef ENT_GENERATED_WORLD_H\n"
        "#define ENT_GENERATED_WORLD_H\n\n"
        "#include <stdbool.h>\n#include <stdint.h>\n#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "typedef struct ent_world ent_world;\n\n";
  os << llvm::formatv("#define ENT_WORLD_BYTES {0}ull\n", layout->totalBytes);
  os << llvm::formatv("#define ENT_WORLD_ALIGNMENT {0}\n\n",
                      WorldLayout::kArenaAlignment);

  os << "// Counts and resources start at zero. Columns are left "
        "uninitialised:\n// nothing reads beyond an archetype's count, and "
        "untouched pages cost\n// no memory.\n"
        "static inline ent_world *ent_world_create(void) {\n"
        "  void *arena = NULL;\n"
        "  if (posix_memalign(&arena, ENT_WORLD_ALIGNMENT, ENT_WORLD_BYTES))\n"
        "    return NULL;\n";
  os << llvm::formatv("  memset(arena, 0, {0});\n", layout->headerBytes);
  os << "  return (ent_world *)arena;\n}\n\n"
        "static inline void ent_world_destroy(ent_world *world) { "
        "free(world); }\n";

  // Entity ids, as EntityScheme chose them. The functions below do exactly
  // what the lowered program does.
  const EntityScheme &scheme = layout->entities;
  auto uintType = [](unsigned bits) {
    return llvm::formatv("uint{0}_t", bits).str();
  };
  os << "\n// Entities: ";
  switch (scheme.kind) {
  case EntityScheme::Rows:
    os << "nothing is ever despawned or moved, so an id is\n// "
          "`archetype << ENT__ROW_BITS | row`.\n";
    break;
  case EntityScheme::Slots:
    os << "entities move but are never despawned, so an id is a\n// "
          "slot of the entity table, which records each entity's location "
          "as\n// `archetype << ENT__ROW_BITS | row`.\n";
    break;
  case EntityScheme::Generational:
    os << "an id is `generation << ENT__SLOT_BITS | slot`. Despawning\n// "
          "bumps the slot's generation, so old ids stop being alive; freed "
          "slots\n// are reused last freed first, through a list threaded "
          "through their\n// locations (`archetype << ENT__ROW_BITS | "
          "row`).\n";
    break;
  }
  os << llvm::formatv("typedef {0} ent_entity;\n", uintType(scheme.idBits));
  os << llvm::formatv("#define ENT_NO_ENTITY UINT{0}_MAX\n", scheme.idBits);
  os << llvm::formatv("#define ENT_ENTITY_CAPACITY {0}\n",
                      layout->entityCapacity);
  os << llvm::formatv("#define ENT__ROW_BITS {0}\n", scheme.rowBits);
  os << "static inline int64_t *ent__counts(const ent_world *world) {\n"
        "  return (int64_t *)world;\n}\n";

  std::string allocate, alive, archetypeOf, rowOf;
  if (scheme.kind == EntityScheme::Rows) {
    allocate = "  return ((ent_entity)archetype << ENT__ROW_BITS) | "
               "(ent_entity)row;\n";
    os << llvm::formatv("#define ENT__ARCHETYPES {0}\n",
                        layout->archetypes.size());
    alive = "  uint64_t archetype = (uint64_t)id >> ENT__ROW_BITS;\n"
            "  uint64_t row = (uint64_t)id & ((UINT64_C(1) << ENT__ROW_BITS) "
            "- 1);\n"
            "  return id != ENT_NO_ENTITY && archetype < ENT__ARCHETYPES &&\n"
            "         (int64_t)row < ent__counts(world)[archetype];\n";
    archetypeOf = "(int32_t)((uint64_t)id >> ENT__ROW_BITS)";
    rowOf = "(int64_t)((uint64_t)id & ((UINT64_C(1) << ENT__ROW_BITS) - 1))";
  } else {
    std::string locationType = uintType(scheme.locationBits);
    os << llvm::formatv("#define ENT__SLOT_BITS {0}\n", scheme.slotBits);
    os << llvm::formatv(
        "#define ENT__NEXT_SLOT ((int64_t *)((char *)world + {0}))\n"
        "#define ENT__LOCATION (({1} *)((char *)world + {2}))\n",
        layout->nextSlotOffset, locationType, layout->locationOffset);
    std::string location = llvm::formatv(
        "  ENT__LOCATION[slot] = ({0})(((uint64_t)archetype << ENT__ROW_BITS) "
        "|\n                             (uint64_t)row);\n",
        locationType);
    std::string inUse = "(int64_t)ent__slot(id) < *ENT__NEXT_SLOT";
    if (scheme.kind == EntityScheme::Slots) {
      allocate = "  int64_t slot = (*ENT__NEXT_SLOT)++;\n" + location +
                 "  return (ent_entity)slot;\n";
      alive = "  return id != ENT_NO_ENTITY && " + inUse + ";\n";
    } else {
      os << llvm::formatv(
          "#define ENT__GENERATION_MASK {0}\n"
          "#define ENT__FREE_HEAD ((int64_t *)((char *)world + {1}))\n"
          "#define ENT__GENERATION (({2} *)((char *)world + {3}))\n",
          (uint64_t(1) << scheme.generationBits) - 1, layout->freeHeadOffset,
          uintType(scheme.generationStorageBits), layout->generationOffset);
      allocate = "  int64_t slot;\n"
                 "  if (*ENT__FREE_HEAD != 0) {\n"
                 "    slot = *ENT__FREE_HEAD - 1;\n"
                 "    *ENT__FREE_HEAD = (int64_t)ENT__LOCATION[slot];\n"
                 "  } else {\n"
                 "    slot = (*ENT__NEXT_SLOT)++;\n"
                 "    ENT__GENERATION[slot] = 0;\n"
                 "  }\n" +
                 location +
                 "  return ((ent_entity)ENT__GENERATION[slot] << "
                 "ENT__SLOT_BITS) |\n         (ent_entity)slot;\n";
      alive = "  return id != ENT_NO_ENTITY && " + inUse +
              " &&\n         ENT__GENERATION[ent__slot(id)] ==\n"
              "             (((uint64_t)id >> ENT__SLOT_BITS) & "
              "ENT__GENERATION_MASK);\n";
    }
    os << "static inline uint64_t ent__slot(ent_entity id) {\n"
          "  return (uint64_t)id & ((UINT64_C(1) << ENT__SLOT_BITS) - 1);\n"
          "}\n";
    archetypeOf = "(int32_t)(ENT__LOCATION[ent__slot(id)] >> ENT__ROW_BITS)";
    rowOf = "(int64_t)(ENT__LOCATION[ent__slot(id)] &\n"
            "                   ((UINT64_C(1) << ENT__ROW_BITS) - 1))";
  }
  os << "static inline ent_entity ent__allocate(ent_world *world, "
        "int32_t archetype,\n"
        "                                       int64_t row) {\n";
  if (scheme.kind == EntityScheme::Rows)
    os << "  (void)world;\n";
  os << allocate << "}\n";
  os << "static inline bool ent_entity_alive(const ent_world *world_, "
        "ent_entity id) {\n"
        "  ent_world *world = (ent_world *)world_;\n"
     << alive << "}\n";
  os << "// The archetype (ENT_ARCHETYPE_<name>) and row of a live entity, "
        "or -1.\n"
        "static inline int32_t ent_entity_archetype(const ent_world *world_,\n"
        "                                           ent_entity id) {\n"
        "  ent_world *world = (ent_world *)world_;\n"
        "  if (!ent_entity_alive(world, id))\n    return -1;\n"
        "  return "
     << archetypeOf
     << ";\n}\n"
        "static inline int64_t ent_entity_row(const ent_world *world_, "
        "ent_entity id) {\n"
        "  ent_world *world = (ent_world *)world_;\n"
        "  if (!ent_entity_alive(world, id))\n    return -1;\n"
        "  return "
     << rowOf << ";\n}\n";

  for (const WorldArchetype &archetype : layout->archetypes) {
    ArchetypeOp archetypeOp = archetype.op;
    std::string name = toIdentifier(archetypeOp.getSymName());
    if (failed(claim(archetypeOp, name)))
      return failure();
    os << llvm::formatv("\n// Archetype @{0}\n", archetypeOp.getSymName());
    os << llvm::formatv("#define ENT_{0}_CAPACITY {1}\n", name,
                        archetype.capacity);
    os << llvm::formatv(
        "static inline int64_t ent_{0}_count(const ent_world *world) {{\n"
        "  return ((const int64_t *)world)[{1}];\n}\n",
        name, archetype.index);
    os << llvm::formatv("#define ENT_ARCHETYPE_{0} {1}\n", name,
                        archetype.index);
    // Spawn one entity: the next row, a new id, optional components absent.
    // The same steps as ent.spawn in the lowered program.
    // A new entity starts without its optional components; for reactive
    // queries it has added and changed every other component (stamped with
    // the current tick, one past the counter) and lost none.
    std::string clearPresence, appendToLogs;
    for (const WorldColumn &column : archetype.columns) {
      if (column.isPresence()) {
        clearPresence +=
            llvm::formatv("  ((uint8_t *)((char *)world + {0}))[n] = 0;\n",
                          column.offset);
      } else if (column.isStamp()) {
        bool happened =
            column.stamp->kind != Trigger::Removed &&
            !archetypeOp.isOptional(
                FlatSymbolRefAttr::get(column.stamp->component));
        clearPresence += llvm::formatv(
            "  ((int64_t *)((char *)world + {0}))[n] = {1};\n", column.offset,
            happened ? llvm::formatv("*(int64_t *)((char *)world + {0}) + 1",
                                     layout->tickOffset)
                           .str()
                     : std::string("0"));
        // A new entity is an event: append it to the stamp's log (the
        // segment of its row's low bits), while the segment has room for
        // its slowest reader; the first to find it full marks it overflowed.
        const WorldLog *log = happened ? layout->findLog(*column.stamp)
                                       : nullptr;
        if (log)
          appendToLogs += llvm::formatv(
              "  {{\n"
              "    int64_t segment = n & {0};\n"
              "    int64_t *counts = (int64_t *)((char *)world + {1}) + "
              "segment * {2};\n"
              "    int64_t pending = counts[0] - counts[1];\n"
              "    if (pending < {3}) {{\n"
              "      int64_t slot = segment * {3} + (counts[0]++ & {4});\n"
              "      ((ent_entity *)((char *)world + {5}))[slot] = id;\n"
              "      ((int64_t *)((char *)world + {6}))[slot] =\n"
              "          *(int64_t *)((char *)world + {7}) + 1;\n"
              "    } else if (pending == {3}) {{\n"
              "      counts[0] = counts[1] + {3} + 1; // overflowed\n"
              "    }\n  }\n",
              log->segments - 1, log->countsOffset,
              WorldLog::kSegmentStride / 8, log->segmentCapacity,
              log->segmentCapacity - 1, log->idsOffset, log->ticksOffset,
              layout->tickOffset);
      }
    }
    os << "// Returns the new entity's id, or ENT_NO_ENTITY if the archetype "
          "is full.\n// Its fields are uninitialised; fill them at "
          "ent_entity_row(world, id).\n";
    std::string storeId =
        scheme.hasIds()
            ? llvm::formatv("  ((ent_entity *)((char *)world + {0}))[n] = "
                            "id;\n",
                            archetype.idOffset)
                  .str()
            : std::string();
    os << llvm::formatv(
        "static inline ent_entity ent_{0}_spawn(ent_world *world) {{\n"
        "  int64_t n = ((int64_t *)world)[{1}];\n"
        "  if (n >= ENT_{0}_CAPACITY)\n    return ENT_NO_ENTITY;\n"
        "{2}"
        "  ent_entity id = ent__allocate(world, {1}, n);\n"
        "{3}{4}"
        "  ((int64_t *)world)[{1}] = n + 1;\n"
        "  return id;\n}\n",
        name, archetype.index, clearPresence, storeId, appendToLogs);
    os << llvm::formatv(
        "// Spawns n entities in consecutive rows; false (and none spawned) "
        "if they\n// do not fit.\n"
        "static inline bool ent_{0}_spawn_n(ent_world *world, int64_t n) {{\n"
        "  if (n < 0 || ent_{0}_count(world) + n > ENT_{0}_CAPACITY)\n"
        "    return false;\n"
        "  for (int64_t i = 0; i < n; ++i)\n"
        "    ent_{0}_spawn(world);\n"
        "  return true;\n}\n",
        name);
    if (scheme.hasIds()) {
      os << llvm::formatv(
          "// The id of the entity in each row.\n"
          "static inline ent_entity *ent_{0}_id(ent_world *world) {{\n"
          "  return (ent_entity *)((char *)world + {1});\n}\n",
          name, archetype.idOffset);
      if (failed(claim(archetypeOp, "ent_" + name + "_id")))
        return failure();
    }
    for (const WorldColumn &column : archetype.columns) {
      // Stamps are the compiler's bookkeeping for reactive queries.
      if (column.isStamp())
        continue;
      bool isPresence = column.isPresence();
      std::string accessor = llvm::formatv(
          "ent_{0}_{1}_{2}", name, toIdentifier(column.component.getValue()),
          isPresence ? std::string("present")
                     : toIdentifier(column.field.getValue()));
      if (failed(claim(archetypeOp, accessor)))
        return failure();
      StringRef cType = isPresence ? "uint8_t" : getCType(column.type);
      os << llvm::formatv(
          "static inline {0} *{1}(ent_world *world) {{\n"
          "  return ({0} *)((char *)world + {2});\n}\n",
          cType, accessor, column.offset);
    }
  }

  for (const WorldResource &resource : layout->resources) {
    ResourceOp resourceOp = resource.op;
    std::string name = toIdentifier(resourceOp.getSymName());
    os << llvm::formatv("\n// Resource @{0}\n", resourceOp.getSymName());
    for (const WorldResourceField &field : resource.fields) {
      std::string accessor = llvm::formatv(
          "ent_{0}_{1}", name, toIdentifier(field.field.getValue()));
      if (failed(claim(resourceOp, accessor)))
        return failure();
      os << llvm::formatv(
          "static inline {0} *{1}(ent_world *world) {{\n"
          "  return ({0} *)((char *)world + {2});\n}\n",
          getCType(field.type), accessor, field.offset);
    }
  }

  os << "\n// Schedules. The lowered function receives the arena as a "
        "memref descriptor.\n"
        "typedef struct {\n  char *allocated;\n  char *aligned;\n"
        "  int64_t offset;\n  int64_t size;\n  int64_t stride;\n"
        "} ent_arena_descriptor;\n";
  for (ScheduleOp schedule : module.getOps<ScheduleOp>()) {
    std::string name = toIdentifier(schedule.getSymName());
    if (failed(claim(schedule, name)))
      return failure();
    SmallVector<std::string> params, args;
    for (BlockArgument arg : schedule.getBody().getArguments()) {
      StringRef cType = getCType(arg.getType());
      if (cType.empty())
        return schedule.emitError("parameter #")
               << arg.getArgNumber() << " has type " << arg.getType()
               << ", which has no C equivalent here";
      params.push_back(llvm::formatv("{0} arg{1}", cType, arg.getArgNumber()));
      args.push_back(llvm::formatv("arg{0}", arg.getArgNumber()));
    }
    std::string declParams, callArgs;
    for (auto [param, arg] : llvm::zip(params, args)) {
      declParams += param + ", ";
      callArgs += arg + ", ";
    }
    os << llvm::formatv("\nvoid _mlir_ciface_{0}({1}ent_arena_descriptor "
                        "*world);\n",
                        schedule.getSymName(), declParams);
    os << llvm::formatv(
        "static inline void ent_{0}(ent_world *world{1}{2}) {{\n"
        "  ent_arena_descriptor arena = {{(char *)world, (char *)world, 0,\n"
        "                                 ENT_WORLD_BYTES, 1};\n"
        "  _mlir_ciface_{3}({4}&arena);\n}\n",
        name, params.empty() ? "" : ", ", llvm::join(params, ", "),
        schedule.getSymName(), callArgs);
  }

  os << "\n#endif // ENT_GENERATED_WORLD_H\n";
  return success();
}

int main(int argc, char **argv) {
  TranslateFromMLIRRegistration header(
      "ent-to-c-header", "Emit the C API of an ent-lang program's world",
      [](Operation *op, raw_ostream &os) -> LogicalResult {
        auto module = dyn_cast<ModuleOp>(op);
        if (!module)
          return op->emitError("expected a module");
        return emitHeader(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<EntDialect, arith::ArithDialect, func::FuncDialect,
                        scf::SCFDialect>();
      });
  return failed(mlirTranslateMain(argc, argv, "ent-lang translation tool"));
}
