#include "Ecs/EcsDialect.h"
#include "Ecs/EcsOps.h"
#include "Ecs/World.h"

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Tools/mlir-translate/MlirTranslateMain.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/FormatVariadic.h"

using namespace mlir;
using namespace mlir::ecs;

/// The C type that holds one element of `type` in world storage.
static StringRef getCType(Type type) {
  if (isa<IndexType>(type))
    return "int64_t";
  if (auto integer = dyn_cast<IntegerType>(type)) {
    switch (integer.getWidth()) {
    case 1:
      return "bool";
    case 8:
      return "int8_t";
    case 16:
      return "int16_t";
    case 32:
      return "int32_t";
    case 64:
      return "int64_t";
    }
  }
  if (type.isF32())
    return "float";
  if (type.isF64())
    return "double";
  return {};
}

/// Replace every character that cannot appear in a C identifier by '_'.
static std::string toIdentifier(StringRef name) {
  std::string result;
  for (char c : name)
    result += llvm::isAlnum(c) ? c : '_';
  if (result.empty() || llvm::isDigit(result.front()))
    result.insert(result.begin(), '_');
  return result;
}

/// Emit the C API of the world and the schedules of `module`: creation,
/// counts, typed column accessors and one entry point per schedule. The
/// header is the only place a host needs to know the layout.
static LogicalResult emitHeader(ModuleOp module, raw_ostream &os) {
  FailureOr<WorldLayout> layout = WorldLayout::compute(module);
  if (failed(layout))
    return failure();

  // Distinct names in the program may map to the same C identifier.
  llvm::StringSet<> names;
  auto claim = [&](Operation *op, const std::string &name) -> LogicalResult {
    if (!names.insert(name).second)
      return op->emitError("C name '") << name << "' is generated twice";
    return success();
  };

  os << "// Generated by ecs-translate --ecs-to-c-header. Do not edit.\n"
        "//\n"
        "// The world is one arena with a layout fixed at compile time. "
        "Create it,\n"
        "// set each archetype's count (at most its capacity), fill the "
        "columns of\n"
        "// entities [0, count), and run schedules on it.\n\n"
        "#ifndef ECS_GENERATED_WORLD_H\n"
        "#define ECS_GENERATED_WORLD_H\n\n"
        "#include <stdbool.h>\n#include <stdint.h>\n#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "typedef struct ecs_world ecs_world;\n\n";
  os << llvm::formatv("#define ECS_WORLD_BYTES {0}ull\n", layout->totalBytes);
  os << llvm::formatv("#define ECS_WORLD_ALIGNMENT {0}\n\n",
                      WorldLayout::kArenaAlignment);

  os << "// Counts and resources start at zero. Columns are left "
        "uninitialised:\n// nothing reads beyond an archetype's count, and "
        "untouched pages cost\n// no memory.\n"
        "static inline ecs_world *ecs_world_create(void) {\n"
        "  void *arena = NULL;\n"
        "  if (posix_memalign(&arena, ECS_WORLD_ALIGNMENT, ECS_WORLD_BYTES))\n"
        "    return NULL;\n";
  os << llvm::formatv("  memset(arena, 0, {0});\n", layout->headerBytes);
  os << "  return (ecs_world *)arena;\n}\n\n"
        "static inline void ecs_world_destroy(ecs_world *world) { "
        "free(world); }\n";

  for (const WorldArchetype &archetype : layout->archetypes) {
    ArchetypeOp archetypeOp = archetype.op;
    std::string name = toIdentifier(archetypeOp.getSymName());
    if (failed(claim(archetypeOp, name)))
      return failure();
    os << llvm::formatv("\n// Archetype @{0}\n", archetypeOp.getSymName());
    os << llvm::formatv("#define ECS_{0}_CAPACITY {1}\n", name,
                        archetype.capacity);
    os << llvm::formatv(
        "static inline int64_t ecs_{0}_count(const ecs_world *world) {{\n"
        "  return ((const int64_t *)world)[{1}];\n}\n",
        name, archetype.index);
    os << llvm::formatv(
        "// Returns false and leaves the count unchanged if n is out of "
        "range.\n"
        "static inline bool ecs_{0}_set_count(ecs_world *world, int64_t n) "
        "{{\n"
        "  if (n < 0 || n > ECS_{0}_CAPACITY)\n    return false;\n"
        "  ((int64_t *)world)[{1}] = n;\n  return true;\n}\n",
        name, archetype.index);
    for (const WorldColumn &column : archetype.columns) {
      std::string accessor =
          llvm::formatv("ecs_{0}_{1}_{2}", name,
                        toIdentifier(column.component.getValue()),
                        toIdentifier(column.field.getValue()));
      if (failed(claim(archetypeOp, accessor)))
        return failure();
      StringRef cType = getCType(column.type);
      os << llvm::formatv(
          "static inline {0} *{1}(ecs_world *world) {{\n"
          "  return ({0} *)((char *)world + {2});\n}\n",
          cType, accessor, column.offset);
    }
  }

  for (const WorldResource &resource : layout->resources) {
    ResourceOp resourceOp = resource.op;
    std::string name = toIdentifier(resourceOp.getSymName());
    os << llvm::formatv("\n// Resource @{0}\n", resourceOp.getSymName());
    for (const WorldResourceField &field : resource.fields) {
      std::string accessor = llvm::formatv(
          "ecs_{0}_{1}", name, toIdentifier(field.field.getValue()));
      if (failed(claim(resourceOp, accessor)))
        return failure();
      os << llvm::formatv(
          "static inline {0} *{1}(ecs_world *world) {{\n"
          "  return ({0} *)((char *)world + {2});\n}\n",
          getCType(field.type), accessor, field.offset);
    }
  }

  os << "\n// Schedules. The lowered function receives the arena as a "
        "memref descriptor.\n"
        "typedef struct {\n  char *allocated;\n  char *aligned;\n"
        "  int64_t offset;\n  int64_t size;\n  int64_t stride;\n"
        "} ecs_arena_descriptor;\n";
  for (ScheduleOp schedule : module.getOps<ScheduleOp>()) {
    std::string name = toIdentifier(schedule.getSymName());
    if (failed(claim(schedule, name)))
      return failure();
    SmallVector<std::string> params, args;
    for (BlockArgument arg : schedule.getBody().getArguments()) {
      StringRef cType = getCType(arg.getType());
      if (cType.empty())
        return schedule.emitError("parameter #")
               << arg.getArgNumber() << " has type " << arg.getType()
               << ", which has no C equivalent here";
      params.push_back(llvm::formatv("{0} arg{1}", cType, arg.getArgNumber()));
      args.push_back(llvm::formatv("arg{0}", arg.getArgNumber()));
    }
    std::string declParams, callArgs;
    for (auto [param, arg] : llvm::zip(params, args)) {
      declParams += param + ", ";
      callArgs += arg + ", ";
    }
    os << llvm::formatv("\nvoid _mlir_ciface_{0}({1}ecs_arena_descriptor "
                        "*world);\n",
                        schedule.getSymName(), declParams);
    os << llvm::formatv(
        "static inline void ecs_{0}(ecs_world *world{1}{2}) {{\n"
        "  ecs_arena_descriptor arena = {{(char *)world, (char *)world, 0,\n"
        "                                 ECS_WORLD_BYTES, 1};\n"
        "  _mlir_ciface_{3}({4}&arena);\n}\n",
        name, params.empty() ? "" : ", ", llvm::join(params, ", "),
        schedule.getSymName(), callArgs);
  }

  os << "\n#endif // ECS_GENERATED_WORLD_H\n";
  return success();
}

int main(int argc, char **argv) {
  TranslateFromMLIRRegistration header(
      "ecs-to-c-header", "Emit the C API of an ECS program's world",
      [](Operation *op, raw_ostream &os) -> LogicalResult {
        auto module = dyn_cast<ModuleOp>(op);
        if (!module)
          return op->emitError("expected a module");
        return emitHeader(module, os);
      },
      [](DialectRegistry &registry) {
        registry.insert<EcsDialect, arith::ArithDialect, func::FuncDialect,
                        scf::SCFDialect>();
      });
  return failed(mlirTranslateMain(argc, argv, "ECS translation tool"));
}
